import { ISimpleCategory } from 'types/category.types'
export const getCategoryByIdPath = (
  path: number[]
): ISimpleCategory | undefined => {
  if (path.length === 1) {
    return categoryTree.find((c) => c.id === path[0])
  }
  if (path.length === 2) {
    const category = categoryTree.find((c) => c.id === path[0])
    return category?.children?.find((sc) => sc.id === path[1])
  }
  return
}
export const getSubCategoryBlockId = (id: number) => {
  return `#sc_${id}`
}
export const categoryTree: ISimpleCategory[] = [
  {
    id: 24,
    parent_id: 0,
    name: 'Acrylic Sign Products',
    is_visible: true,
    url: '/acrylic-sign-products/',
    children: [
      {
        id: 101,
        parent_id: 24,
        name: 'Print Protectors',
        is_visible: true,
        url: '/acrylic-sign-products/print-protectors/',
        children: [],
      },
      {
        id: 39,
        parent_id: 24,
        name: 'Business card holder',
        is_visible: true,
        url: '/acrylic-sign-products/business-card-holder/',
        images: [
          {
            src: '/logo/logo.png',
            width: 1,
            height: 1,
          },
          { src: '/bg/home.png', width: 4, height: 2 },
          { src: '/bg/sign-up.jpeg', width: 8, height: 5 },
        ],
        children: [],
      },
      {
        id: 40,
        parent_id: 24,
        name: 'Literature & Brochure holder',
        is_visible: true,
        url: '/acrylic-sign-products/literature-brochure-holder/',
        children: [],
      },
      {
        id: 41,
        parent_id: 24,
        name: 'Countertop Sign Holder',
        is_visible: true,
        url: '/acrylic-sign-products/countertop-sign-holder/',
        children: [
          {
            id: 82,
            parent_id: 41,
            name: 'Slanted Sign Holder',
            is_visible: true,
            url:
              '/acrylic-sign-products/countertop-sign-holder/slanted-sign-holder/',
            children: [],
          },
          {
            id: 83,
            parent_id: 41,
            name: 'Magnetic Sign Holder',
            is_visible: true,
            url:
              '/acrylic-sign-products/countertop-sign-holder/magnetic-sign-holder/',
            children: [],
          },
          {
            id: 84,
            parent_id: 41,
            name: 'Double Sided Tent Sign Holder',
            is_visible: true,
            url:
              '/acrylic-sign-products/countertop-sign-holder/double-sided-tent-sign-holder/',
            children: [],
          },
          {
            id: 85,
            parent_id: 41,
            name: 'Other',
            is_visible: true,
            url: '/acrylic-sign-products/countertop-sign-holder/other/',
            children: [],
          },
          {
            id: 81,
            parent_id: 41,
            name: 'T-Base Sign Holder',
            is_visible: true,
            url:
              '/acrylic-sign-products/countertop-sign-holder/t-base-sign-holder/',
            children: [],
          },
        ],
      },
      {
        id: 42,
        parent_id: 24,
        name: 'Clear Ballot Boxes',
        is_visible: true,
        url: '/acrylic-sign-products/clear-ballot-boxes/',
        children: [],
      },
    ],
  },
  {
    id: 25,
    parent_id: 0,
    name: 'Backdrop Stands & Pop–Up Display',
    is_visible: true,
    url: '/backdrop-stands-pop-up-display/',
    children: [
      {
        id: 43,
        parent_id: 25,
        name: 'Telescoping Backdrop Banner Stands',
        is_visible: true,
        url:
          '/backdrop-stands-pop-up-display/telescoping-backdrop-banner-stands/',
        children: [],
      },
      {
        id: 44,
        parent_id: 25,
        name: 'BEAVERTM  Pop-Up Display System',
        is_visible: true,
        url: '/backdrop-stands-pop-up-display/beavertm-pop-up-display-system/',
        children: [
          {
            id: 86,
            parent_id: 44,
            name: 'Curve Table Top',
            is_visible: true,
            url:
              '/backdrop-stands-pop-up-display/beavertm-pop-up-display-system/curve-table-top/',
            children: [],
          },
          {
            id: 87,
            parent_id: 44,
            name: 'Curve 8-FT. High',
            is_visible: true,
            url:
              '/backdrop-stands-pop-up-display/beavertm-pop-up-display-system/curve-8-ft-high/',
            children: [],
          },
          {
            id: 88,
            parent_id: 44,
            name: 'Straight 8-FT. High',
            is_visible: true,
            url:
              '/backdrop-stands-pop-up-display/beavertm-pop-up-display-system/straight-8-ft-high/',
            children: [],
          },
          {
            id: 89,
            parent_id: 44,
            name: 'Parts',
            is_visible: true,
            url:
              '/backdrop-stands-pop-up-display/beavertm-pop-up-display-system/parts/',
            children: [],
          },
        ],
      },
      {
        id: 45,
        parent_id: 25,
        name: 'Pop-Up Banner Stand',
        is_visible: true,
        url: '/backdrop-stands-pop-up-display/pop-up-banner-stand/',
        children: [],
      },
    ],
  },
  {
    id: 26,
    parent_id: 0,
    name: 'Banner Stands',
    is_visible: true,
    url: '/banner-stands/',
    children: [
      {
        id: 46,
        parent_id: 26,
        name: 'X-Banner Stand',
        is_visible: true,
        url: '/banner-stands/x-banner-stand/',
        children: [],
      },
      {
        id: 47,
        parent_id: 26,
        name: 'Retractable Banner Stand',
        is_visible: true,
        url: '/banner-stands/retractable-banner-stand/',
        children: [],
      },
      {
        id: 48,
        parent_id: 26,
        name: 'Floor Standing Banner Stand',
        is_visible: true,
        url: '/banner-stands/floor-standing-banner-stand/',
        children: [],
      },
    ],
  },
  {
    id: 27,
    parent_id: 0,
    name: 'Brochure & Newspaper Holders',
    is_visible: true,
    url: '/brochure-newspaper-holders/',
    children: [
      {
        id: 49,
        parent_id: 27,
        name: 'Brochure / Magazine Holder',
        is_visible: true,
        url: '/brochure-newspaper-holders/brochure-magazine-holder/',
        children: [],
      },
      {
        id: 50,
        parent_id: 27,
        name: 'Newspaper Holders',
        is_visible: true,
        url: '/brochure-newspaper-holders/newspaper-holders/',
        children: [],
      },
    ],
  },
  {
    id: 28,
    parent_id: 0,
    name: 'Crowd Control Systems',
    is_visible: true,
    url: '/crowd-control-systems/',
    children: [
      {
        id: 51,
        parent_id: 28,
        name: '4-Way Stanchion with Retractable Belt',
        is_visible: true,
        url: '/crowd-control-systems/4-way-stanchion-with-retractable-belt/',
        children: [],
      },
      {
        id: 52,
        parent_id: 28,
        name: 'Stanchion Sign Holder',
        is_visible: true,
        url: '/crowd-control-systems/stanchion-sign-holder/',
        children: [],
      },
      {
        id: 53,
        parent_id: 28,
        name: 'Sphere Post Stanchion & Rope',
        is_visible: true,
        url: '/crowd-control-systems/sphere-post-stanchion-rope/',
        children: [],
      },
    ],
  },
  {
    id: 29,
    parent_id: 0,
    name: 'Flags',
    is_visible: true,
    url: '/flags/',
    children: [
      {
        id: 54,
        parent_id: 29,
        name: 'Tear Drop Flag Pole',
        is_visible: true,
        url: '/flags/tear-drop-flag-pole/',
        children: [],
      },
      {
        id: 55,
        parent_id: 29,
        name: 'Feather Flag Pole',
        is_visible: true,
        url: '/flags/feather-flag-pole/',
        children: [],
      },
      {
        id: 56,
        parent_id: 29,
        name: 'Block Flag Pole',
        is_visible: true,
        url: '/flags/block-flag-pole/',
        children: [],
      },
      {
        id: 57,
        parent_id: 29,
        name: 'Flag Parts',
        is_visible: true,
        url: '/flags/flag-parts/',
        children: [],
      },
    ],
  },
  {
    id: 30,
    parent_id: 0,
    name: 'Floor Sign Holder',
    is_visible: true,
    url: '/floor-sign-holder/',
    children: [
      {
        id: 58,
        parent_id: 30,
        name: 'Easel',
        is_visible: true,
        url: '/floor-sign-holder/easel/',
        children: [],
      },
      {
        id: 59,
        parent_id: 30,
        name: 'Large Scale Graphic Support',
        is_visible: true,
        url: '/floor-sign-holder/large-scale-graphic-support/',
        children: [],
      },
      {
        id: 60,
        parent_id: 30,
        name: 'Floor Sign Holder',
        is_visible: true,
        url: '/floor-sign-holder/floor-sign-holder/',
        children: [],
      },
      {
        id: 61,
        parent_id: 30,
        name: 'Sign Holder',
        is_visible: true,
        url: '/floor-sign-holder/sign-holder/',
        children: [],
      },
      {
        id: 62,
        parent_id: 30,
        name: 'Bulletin Sign holder',
        is_visible: true,
        url: '/floor-sign-holder/bulletin-sign-holder/',
        children: [],
      },
    ],
  },
  {
    id: 31,
    parent_id: 0,
    name: 'Metal A-Frame Sign Holders',
    is_visible: true,
    url: '/metal-a-frame-sign-holders/',
    children: [
      {
        id: 63,
        parent_id: 31,
        name: 'Angled Metal A-Frames',
        is_visible: true,
        url: '/metal-a-frame-sign-holders/angled-metal-a-frames/',
        children: [],
      },
      {
        id: 64,
        parent_id: 31,
        name: 'Heavy Duty Metal A-Frame ',
        is_visible: true,
        url: '/metal-a-frame-sign-holders/heavy-duty-metal-a-frame/',
        children: [],
      },
      {
        id: 65,
        parent_id: 31,
        name: 'Chalkboard A-Frame',
        is_visible: true,
        url: '/metal-a-frame-sign-holders/chalkboard-a-frame/',
        children: [],
      },
      {
        id: 66,
        parent_id: 31,
        name: 'Aluminum Snap A-Frame',
        is_visible: true,
        url: '/metal-a-frame-sign-holders/aluminum-snap-a-frame/',
        children: [],
      },
    ],
  },
  {
    id: 32,
    parent_id: 0,
    name: 'Metal Lawn Sign Holders',
    is_visible: true,
    url: '/metal-lawn-sign-holders/',
    children: [
      {
        id: 67,
        parent_id: 32,
        name: 'Metal Lawn Post',
        is_visible: true,
        url: '/metal-lawn-sign-holders/metal-lawn-post/',
        children: [],
      },
      {
        id: 68,
        parent_id: 32,
        name: 'Metal Lawn Stake',
        is_visible: true,
        url: '/metal-lawn-sign-holders/metal-lawn-stake/',
        children: [],
      },
    ],
  },
  {
    id: 33,
    parent_id: 0,
    name: 'PVC A-Boards',
    is_visible: true,
    url: '/pvc-a-boards/',
    children: [
      {
        id: 69,
        parent_id: 33,
        name: 'Metal Edge PVC A-Board ',
        is_visible: true,
        url: '/pvc-a-boards/metal-edge-pvc-a-board/',
        children: [],
      },
      {
        id: 70,
        parent_id: 33,
        name: 'Plastic Hinge Handle ',
        is_visible: true,
        url: '/pvc-a-boards/plastic-hinge-handle/',
        children: [],
      },
    ],
  },
  {
    id: 34,
    parent_id: 0,
    name: 'Sign Brackets & Banner Hangers',
    is_visible: true,
    url: '/sign-brackets-banner-hangers/',
    children: [
      {
        id: 71,
        parent_id: 34,
        name: 'Architectural Sign Brackets',
        is_visible: true,
        url: '/sign-brackets-banner-hangers/architectural-sign-brackets/',
        children: [],
      },
    ],
  },
  {
    id: 35,
    parent_id: 0,
    name: 'Frame Sign Holders',
    is_visible: true,
    url: '/frame-sign-holders/',
    children: [
      {
        id: 72,
        parent_id: 35,
        name: 'Snap Frame Sign Holder',
        is_visible: true,
        url: '/frame-sign-holders/snap-frame-sign-holder/',
        children: [
          {
            id: 90,
            parent_id: 72,
            name: 'Mitered Corner Snap Frame',
            is_visible: true,
            url:
              '/frame-sign-holders/snap-frame-sign-holder/mitered-corner-snap-frame/',
            children: [],
          },
          {
            id: 91,
            parent_id: 72,
            name: 'Round Corner Snap Frame',
            is_visible: true,
            url:
              '/frame-sign-holders/snap-frame-sign-holder/round-corner-snap-frame/',
            children: [],
          },
        ],
      },
      {
        id: 73,
        parent_id: 35,
        name: 'Magnetic Sign holder ',
        is_visible: true,
        url: '/frame-sign-holders/magnetic-sign-holder/',
        children: [],
      },
    ],
  },
  {
    id: 36,
    parent_id: 0,
    name: 'Standoffs & Cable wire System',
    is_visible: true,
    url: '/standoffs-cable-wire-system/',
    children: [
      {
        id: 74,
        parent_id: 36,
        name: 'Standoffs',
        is_visible: true,
        url: '/standoffs-cable-wire-system/standoffs/',
        children: [
          {
            id: 92,
            parent_id: 74,
            name: 'Aluminum Finish',
            is_visible: true,
            url: '/standoffs-cable-wire-system/standoffs/aluminum-finish/',
            children: [],
          },
          {
            id: 93,
            parent_id: 74,
            name: 'Chrome Finish',
            is_visible: true,
            url: '/standoffs-cable-wire-system/standoffs/chrome-finish/',
            children: [],
          },
          {
            id: 94,
            parent_id: 74,
            name: 'Stainless Steel Finish',
            is_visible: true,
            url:
              '/standoffs-cable-wire-system/standoffs/stainless-steel-finish/',
            children: [],
          },
          {
            id: 95,
            parent_id: 74,
            name: 'Foil Finish',
            is_visible: true,
            url: '/standoffs-cable-wire-system/standoffs/foil-finish/',
            children: [],
          },
          {
            id: 96,
            parent_id: 74,
            name: 'Edge Grips',
            is_visible: true,
            url: '/standoffs-cable-wire-system/standoffs/edge-grips/',
            children: [],
          },
          {
            id: 97,
            parent_id: 74,
            name: 'Caps',
            is_visible: true,
            url: '/standoffs-cable-wire-system/standoffs/caps/',
            children: [],
          },
        ],
      },
      {
        id: 75,
        parent_id: 36,
        name: 'Cable–Wire System',
        is_visible: true,
        url: '/standoffs-cable-wire-system/cable-wire-system/',
        children: [
          {
            id: 98,
            parent_id: 75,
            name: 'Wall Mount Bracket',
            is_visible: true,
            url:
              '/standoffs-cable-wire-system/cable-wire-system/wall-mount-bracket/',
            children: [],
          },
          {
            id: 99,
            parent_id: 75,
            name: 'Clamps',
            is_visible: true,
            url: '/standoffs-cable-wire-system/cable-wire-system/clamps/',
            children: [],
          },
          {
            id: 100,
            parent_id: 75,
            name: 'Connector Units',
            is_visible: true,
            url:
              '/standoffs-cable-wire-system/cable-wire-system/connector-units/',
            children: [],
          },
        ],
      },
      {
        id: 76,
        parent_id: 36,
        name: 'Rod Display System',
        is_visible: true,
        url: '/standoffs-cable-wire-system/rod-display-system/',
        children: [],
      },
    ],
  },
  {
    id: 37,
    parent_id: 0,
    name: 'Way–Finding Signs',
    is_visible: true,
    url: '/way-finding-signs/',
    children: [
      {
        id: 77,
        parent_id: 37,
        name: 'Washroom Sign',
        is_visible: true,
        url: '/way-finding-signs/washroom-sign/',
        children: [],
      },
      {
        id: 78,
        parent_id: 37,
        name: '“PUSH” & “PULL” Sign',
        is_visible: true,
        url: '/way-finding-signs/push-pull-sign/',
        children: [],
      },
      {
        id: 79,
        parent_id: 37,
        name: '“NO SMOKING” Sign',
        is_visible: true,
        url: '/way-finding-signs/no-smoking-sign/',
        children: [],
      },
      {
        id: 80,
        parent_id: 37,
        name: 'Aluminum Sign Panel',
        is_visible: true,
        url: '/way-finding-signs/aluminum-sign-panel/',
        children: [],
      },
    ],
  },
  {
    id: 38,
    parent_id: 0,
    name: 'Wind Resistant Sign Holders',
    is_visible: true,
    url: '/wind-resistant-sign-holders/',
    children: [],
  },
]
